apiVersion: v1
kind: Service
metadata:
  name: veciturno-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: veciturno
spec:
  selector:
    app: veciturno
  ports:
    - protocol: TCP
      name: web
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
