apiVersion: v2
name: veciturno
appVersion: "1.0.0"
version: 1.0.0
description: Gestión de turnos rotativos de limpieza de la comunidad con bot de WhatsApp autohospedado.
icon: https://app.cdn.olares.com/appstore/default/icon.webp
